### ISSUE TITLE
use github-clone-repo to clone templates

### ISSUE THREAD

**Issue by DevAndromeda** [CesiumLabs/frost#5]
We should use **[github-clone-repo](https://github.com/DevSnowflake/github-clone-repo)** to clone template rather than spawning git command. **[github-clone-repo](https://github.com/DevSnowflake/github-clone-repo)** does not require you to have git installed. To remove the directory, we can use **[rimraf](https://npmjs.com/package/rimraf)**.

# File that needs to be changed:

https://github.com/DevSnowflake/frost/blob/f197eadf69744b12f6c95aa53643bce7c959ed6d/src/new/index.ts#L1-L38

# github-clone-repo example:

```js
const clone = require("github-clone-repo");

clone({
    owner: "DevSnowflake",
    repository: "frost",
    branch: "main",
    outPath: `${__dirname}/output`
}).then(status => {
    if (status) console.log("Success!");
    else console.log("Failed :(");
});
```

**Comment by rhygg** [comment]
Will be done, in the next release 👍🏻
